### ISSUE TITLE
successor or derivative of SharpChess respectively Sharper

### ISSUE THREAD

**Issue by yellow-panther** [jfern2011/chess#1]
Hello,

has your engine anything in common with **SharpChess  or #Chess** https://chessprogramming.wikispaces.com/Sharp+Chess respectively **Sharper** https://chessprogramming.wikispaces.com/Sharper

cf. Wayback 
Archive http://www.albert.nu/default.asp?sub=programs/default.asp?sub=sharpchess/main.htm
https://web.archive.org/web/20061014115710/http://www.albert.nu/default.asp?sub=programs/default.asp%3Fsub=sharper/main.htm

**Comment by jfern2011** [comment]
Nope. This engine is written completely from scratch, independently of SharpChess or Sharper
